<?php

declare(strict_types=1);

namespace Lucasp\Loom\Tools;

use Illuminate\JsonSchema\JsonSchemaTypeFactory;
use Illuminate\JsonSchema\Types\Type;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tool;
use Lucasp\Loom\Mcp\LoomMcpServer;
use ReflectionClass;
use ReflectionProperty;
use RuntimeException;

/**
 * Builds the generated regions of the reference pages from their sources:
 * the JSON schema, the MCP tool classes and config/loom.php. A page holds
 * hand-written prose around `<!-- generated:NAME -->` ... `<!-- /generated:NAME -->`
 * markers; only the text between the markers is ever rewritten.
 */
final class ReferencePages
{
    /** @var array<string, array{page: string, build: string}> region name => page + builder method */
    private const REGIONS = [
        'schema' => ['page' => 'docs/reference/schema.md', 'build' => 'schema'],
        'mcp-tools' => ['page' => 'docs/reference/mcp-tools.md', 'build' => 'mcpTools'],
        'config-scan' => ['page' => 'docs/reference/scan-config.md', 'build' => 'configScan'],
        'config-ui' => ['page' => 'docs/reference/ui-config.md', 'build' => 'configUi'],
    ];

    public function __construct(private readonly string $root) {}

    /**
     * Every page with its regions regenerated, keyed by path relative to the root.
     *
     * @return array<string, string>
     */
    public function render(): array
    {
        $pages = [];
        foreach (self::REGIONS as $name => $region) {
            $page = $region['page'];
            $current = $pages[$page] ?? $this->read($page);
            $pages[$page] = $this->splice($current, $name, $this->{$region['build']}(), $page);
        }

        return $pages;
    }

    /**
     * Writes every page whose generated regions differ; returns the changed paths.
     *
     * @return list<string>
     */
    public function write(): array
    {
        $changed = [];
        foreach ($this->render() as $page => $content) {
            if ($content !== $this->read($page)) {
                file_put_contents($this->root.'/'.$page, $content);
                $changed[] = $page;
            }
        }

        return $changed;
    }

    private function read(string $page): string
    {
        $path = $this->root.'/'.$page;
        if (! is_file($path)) {
            throw new RuntimeException("Missing page {$page}");
        }

        return (string) file_get_contents($path);
    }

    private function splice(string $page, string $name, string $body, string $path): string
    {
        $start = "<!-- generated:{$name} -->";
        $end = "<!-- /generated:{$name} -->";
        $from = strpos($page, $start);
        $to = strpos($page, $end);
        if ($from === false || $to === false || $to < $from) {
            throw new RuntimeException("{$path} lacks the {$name} generated region markers");
        }

        $notice = '<!-- Generated by `composer docs:generate`; edit the source, not this block. -->';

        return substr($page, 0, $from + strlen($start))."\n".$notice."\n\n".trim($body)."\n".substr($page, $to);
    }

    // ---- schema -----------------------------------------------------------

    /** @var array<string, mixed> */
    private array $schema = [];

    /** @var list<string> defs that are the entry shape of a top-level section */
    private array $sectionDefs = [];

    private function schema(): string
    {
        $path = $this->root.'/schema/loom-index.schema.json';
        $this->schema = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
        $defs = $this->schema['$defs'];
        $this->sectionDefs = array_values(array_filter(Arr::map(
            $this->schema['properties'],
            static fn (array $p): ?string => isset($p['items']['$ref']) ? Str::after($p['items']['$ref'], '#/$defs/') : null,
        )));

        $out = ['## Top-level fields', '', $this->schemaDescription($this->schema)];
        $out[] = $this->fieldTable($this->schema, '');

        foreach ($this->schema['properties'] as $key => $property) {
            $ref = $property['items']['$ref'] ?? null;
            if ($ref === null) {
                continue;
            }
            $def = Str::after($ref, '#/$defs/');
            $out[] = $this->defSection("## `{$key}[]`", "{$key}[]", $defs[$def]);
        }

        $out[] = '## Shared shapes';
        $out[] = 'Referenced from several sections above.';
        foreach ($defs as $name => $def) {
            if (in_array($name, $this->sectionDefs, true)) {
                continue;
            }
            $out[] = $this->defSection("### `{$name}`", $name, $def);
        }

        return implode("\n\n", array_filter($out, static fn (string $s): bool => $s !== ''));
    }

    /** @param array<string, mixed> $def */
    private function defSection(string $heading, string $path, array $def): string
    {
        $parts = [$heading, $this->schemaDescription($def), isset($def['properties']) ? $this->fieldTable($def, $path) : ''];

        return implode("\n\n", array_filter($parts, static fn (string $s): bool => $s !== ''));
    }

    /** @param array<string, mixed> $node */
    private function schemaDescription(array $node): string
    {
        return (string) ($node['description'] ?? '');
    }

    /**
     * A field table for an object node, followed by tables for inline nested objects.
     *
     * @param  array<string, mixed>  $object
     */
    private function fieldTable(array $object, string $path): string
    {
        $required = $object['required'] ?? [];
        $rows = ['| Field | Type | Description |', '| --- | --- | --- |'];
        $nested = [];

        foreach ($object['properties'] as $field => $node) {
            [$type, $inline] = $this->typeOf($node);
            $rows[] = sprintf(
                '| `%s`%s | %s | %s |',
                $field,
                in_array($field, $required, true) ? '' : '?',
                $type,
                $this->cell($node['description'] ?? ''),
            );
            if ($inline !== null && isset($inline['properties'])) {
                $suffix = ($node['type'] ?? null) === 'array' ? '[]' : '';
                $nested[] = $this->subTable($inline, ($path === '' ? '' : "{$path}.").$field.$suffix);
            }
        }

        return implode("\n", $rows).($nested === [] ? '' : "\n\n".implode("\n\n", $nested));
    }

    /**
     * @param  array<string, mixed>  $object
     */
    private function subTable(array $object, string $path): string
    {
        return "`{$path}`\n\n".$this->fieldTable($object, $path);
    }

    /**
     * Human type for a schema node, plus the inline object schema it carries, if any.
     *
     * @param  array<string, mixed>  $node
     * @return array{0: string, 1: array<string, mixed>|null}
     */
    private function typeOf(array $node): array
    {
        if (isset($node['$ref'])) {
            return [$this->refLabel($node['$ref']), null];
        }
        if (isset($node['oneOf'])) {
            $labels = [];
            $inline = null;
            foreach ($node['oneOf'] as $branch) {
                [$label, $branchInline] = $this->typeOf($branch);
                $labels[] = $label;
                $inline ??= $branchInline;
            }
            $null = in_array('null', $labels, true);
            $rest = array_values(array_diff($labels, ['null']));

            return [implode(' or ', $rest).($null ? ' or null' : ''), $inline];
        }
        if (isset($node['enum'])) {
            return ['one of '.implode(', ', Arr::map($node['enum'], static fn (string $v): string => "`{$v}`")), null];
        }

        $type = $node['type'] ?? 'any';
        if (is_array($type)) {
            return [implode(' or ', $type), null];
        }
        if ($type === 'array') {
            $items = $node['items'] ?? [];
            [$label, $inline] = $this->typeOf($items);

            return ["array of {$label}", $inline];
        }
        if ($type === 'object') {
            return ['object', $node];
        }
        if ($type === 'integer' && isset($node['minimum'])) {
            return ["integer ≥ {$node['minimum']}", null];
        }

        return [(string) $type, null];
    }

    private function refLabel(string $ref): string
    {
        $name = Str::after($ref, '#/$defs/');

        return match (true) {
            $name === 'relativePath' => 'path',
            in_array($name, $this->sectionDefs, true) => 'object',
            default => '['.$name.'](#'.Str::lower($name).')',
        };
    }

    private function cell(string $text): string
    {
        return str_replace(['|', "\n"], ['\|', ' '], $text);
    }

    // ---- MCP tools --------------------------------------------------------

    private function mcpTools(): string
    {
        $classes = (new ReflectionProperty(LoomMcpServer::class, 'tools'))->getDefaultValue();
        $tools = [];
        foreach ($classes as $class) {
            $reflection = new ReflectionClass($class);
            $name = $reflection->getAttributes(Name::class)[0]->newInstance()->value;
            $description = $reflection->getAttributes(Description::class)[0]->newInstance()->value;
            $tool = $reflection->newInstanceWithoutConstructor();
            if (! $tool instanceof Tool) {
                throw new RuntimeException("{$class} is not an MCP tool");
            }
            $inputs = $tool->schema(new JsonSchemaTypeFactory);
            $tools[] = [$name, $description, $inputs];
        }

        $sections = [];
        foreach ($tools as [$name, $description, $inputs]) {
            $sections[] = $this->toolSection($name, $description, $inputs);
        }

        return implode("\n\n", $sections);
    }

    /**
     * @param  array<string, Type>  $inputs
     */
    private function toolSection(string $name, string $description, array $inputs): string
    {
        $out = ["### `{$name}`", '', $description, ''];
        if ($inputs === []) {
            $out[] = 'No inputs.';

            return implode("\n", $out);
        }

        $out[] = '| Input | Type | Required | Default | Notes |';
        $out[] = '| --- | --- | --- | --- | --- |';
        foreach ($inputs as $key => $type) {
            $array = $type->toArray();
            $required = (new ReflectionProperty(Type::class, 'required'))->getValue($type) === true;
            $notes = $array['description'] ?? '';
            if (isset($array['enum'])) {
                $values = implode(', ', Arr::map($array['enum'], static fn (string $v): string => "`{$v}`"));
                $notes = rtrim($notes, '.').'. One of '.$values.'.';
            }
            $out[] = sprintf(
                '| `%s` | %s | %s | %s | %s |',
                $key,
                $array['type'] ?? 'any',
                $required ? 'yes' : 'no',
                array_key_exists('default', $array) ? '`'.json_encode($array['default']).'`' : 'none',
                $this->cell($notes),
            );
        }

        return implode("\n", $out);
    }

    // ---- config -----------------------------------------------------------

    private function configScan(): string
    {
        return $this->configTable(['scan.']);
    }

    private function configUi(): string
    {
        return $this->configTable(['index_path', 'ui.', 'mcp.']);
    }

    /**
     * @param  list<string>  $prefixes  dotted keys to include; a trailing dot takes a whole group
     */
    private function configTable(array $prefixes): string
    {
        $rows = ['| Key | Env variable | Default | Meaning |', '| --- | --- | --- | --- |'];
        foreach ($this->configEntries() as $entry) {
            $match = false;
            foreach ($prefixes as $prefix) {
                $match = $match || ($prefix === $entry['key'] || (str_ends_with($prefix, '.') && str_starts_with($entry['key'], $prefix)));
            }
            if ($match) {
                $rows[] = sprintf(
                    '| `%s` | %s | `%s` | %s |',
                    $entry['key'],
                    $entry['env'] === null ? 'none' : "`{$entry['env']}`",
                    $entry['default'],
                    $this->cell($entry['comment']),
                );
            }
        }

        return implode("\n", $rows);
    }

    /**
     * Reads config/loom.php: dotted key, env variable, default and the comment above it.
     *
     * @return list<array{key: string, env: string|null, default: string, comment: string}>
     */
    private function configEntries(): array
    {
        $path = $this->root.'/config/loom.php';
        $config = require $path;
        $lines = file($path, FILE_IGNORE_NEW_LINES) ?: [];
        $entries = [];
        $group = null;
        $comment = [];

        foreach ($lines as $line) {
            $trim = trim($line);
            if (str_starts_with($trim, '//')) {
                $comment[] = trim(substr($trim, 2));

                continue;
            }
            if (preg_match("/^'([a-z_]+)' => \[\s*$/", $trim, $m) === 1 && str_starts_with($line, '    \'')) {
                $group = $m[1];
                $comment = [];

                continue;
            }
            if (preg_match("/^'([a-z_]+)' =>/", $trim, $m) === 1) {
                $top = ! str_starts_with($line, '        ');
                $key = $top ? $m[1] : "{$group}.{$m[1]}";
                $value = $top ? $config[$m[1]] : $config[$group][$m[1]];
                $env = preg_match("/env\('([A-Z_]+)'/", $trim, $e) === 1 ? $e[1] : null;
                $entries[] = [
                    'key' => $key,
                    'env' => $env,
                    'default' => $this->exportDefault($value),
                    'comment' => implode(' ', $comment),
                ];
                $comment = [];

                continue;
            }
            if ($trim === '') {
                $comment = [];
            }
        }

        return $entries;
    }

    private function exportDefault(mixed $value): string
    {
        return match (true) {
            $value === null => 'null',
            is_bool($value) => $value ? 'true' : 'false',
            is_array($value) => '['.implode(', ', Arr::map($value, fn (mixed $v): string => $this->exportDefault($v))).']',
            is_int($value) => (string) $value,
            default => "'".(string) $value."'",
        };
    }
}
